# Generated by Django 5.1.4 on 2025-02-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('jeans', 'Jeans'), ('jackets', 'Jackets'), ('shoes', 'Shoes'), ('dresses', 'Dresses'), ('tops', 'Tops'), ('bottoms', 'Bottoms')], max_length=50),
        ),
    ]
