# Generated by Django 5.1.4 on 2025-02-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image_name',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
