# Generated by Django 5.1.4 on 2025-03-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_alter_userprofile_height_alter_userprofile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='body_shape',
            field=models.CharField(blank=True, choices=[('hourglass', 'Hourglass'), ('pear', 'Pear'), ('apple', 'Apple'), ('rectangle', 'Rectangle')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kilograms', null=True),
        ),
    ]
