# Generated by Django 5.1.4 on 2025-03-09 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_remove_orderitem_price_orderitem_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_at',
        ),
        migrations.AddField(
            model_name='cart',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
