# Generated by Django 5.1.4 on 2025-03-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_remove_cart_added_at_cart_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('qr_code', 'QR Code'), ('card', 'Credit/Debit Card')], default='pending', max_length=50),
        ),
    ]
