# Generated by Django 5.1.4 on 2025-03-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0016_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('t-shirts', 'T-Shirts'), ('polo-shirts', 'Polo Shirt'), ('jeans', 'Jeans'), ('jackets', 'Jackets'), ('blazers', 'Blazers'), ('dresses', 'Dresses'), ('hoodies-sweatshirts', 'Hoodies | Sweatshirts'), ('sweaters-cardigans', 'Sweater | Cardigans'), ('tops', 'Tops'), ('bottoms', 'Bottoms'), ('shoes', 'Shoes'), ('bags', 'Bags'), ('accessories', 'Accessories'), ('perfumer', 'Perfume')], max_length=50),
        ),
    ]
