# Generated by Django 5.1.4 on 2025-03-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0017_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('t-shirts', 'T-Shirts'), ('polo-shirts', 'Polo Shirt'), ('jeans', 'Jeans'), ('jackets', 'Jackets'), ('blazers', 'Blazers'), ('dresses', 'Dresses'), ('trousers', 'Trousers'), ('hoodies-sweatshirts', 'Hoodies | Sweatshirts'), ('sweaters-cardigans', 'Sweater | Cardigans'), ('tops', 'Tops'), ('shorts', 'Shorts'), ('shoes', 'Shoes'), ('bags', 'Bags'), ('accessories', 'Accessories'), ('perfume', 'Perfume')], max_length=50),
        ),
    ]
