# Generated by Django 5.1.4 on 2025-03-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0018_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=50),
        ),
    ]
