# Generated by Django 5.1.4 on 2025-05-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0020_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('t_shirts', 'T-Shirts'), ('polo_shirts', 'Polo Shirt'), ('jeans', 'Jeans'), ('jackets', 'Jackets'), ('blazers', 'Blazers'), ('dresses', 'Dresses'), ('trousers', 'Trousers'), ('hoodies_sweatshirts', 'Hoodies | Sweatshirts'), ('sweaters_cardigans', 'Sweater | Cardigans'), ('tops', 'Tops'), ('shorts', 'Shorts'), ('shoes', 'Shoes'), ('bags', 'Bags'), ('accessories', 'Accessories'), ('perfume', 'Perfume')], max_length=50),
        ),
    ]
