# Generated by Django 5.1.4 on 2025-05-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0021_alter_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/about/')),
            ],
        ),
    ]
