# Generated by Django 5.1.4 on 2025-05-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0022_abouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/abouts/'),
        ),
    ]
