# Generated by Django 5.1.4 on 2025-05-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0023_alter_abouts_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abouts',
            new_name='About',
        ),
    ]
