# Generated by Django 5.2.1 on 2025-08-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0024_rename_abouts_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
