# Generated by Django 5.2.1 on 2025-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0025_alter_userprofile_email_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_bank',
            field=models.CharField(blank=True, choices=[('aba', 'ABA Bank'), ('canadia', 'CANADIA Bank'), ('aceleda', 'ACELEDA Bank')], max_length=50, null=True),
        ),
    ]
